server.port=8080
spring.datasource.url=jdbc:mysql://localhost/crud?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.dll-auto=update
#none = No creo tablas , si pongo update las actualiza
